# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pciang.github.io
email: peterch1ang@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A competitive programmer, an amateur gamer, and an undergraduate at Nanyang Technology University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pciang.github.io/" # the base hostname & protocol for your site
twitter_username: pc1ang
github_username:  pciang

# Build settings
markdown: kramdown
