# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to pciang.github.io
email: peterch1ang@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
	My personal blogs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.com/pciang" # the base hostname & protocol for your site
twitter_username: pc1ang
github_username:  pciang

# Build settings
markdown: kramdown
